development:
  adapter: postgresql
  encoding: unicode
  database: tracking_development
  username: ec2-user
  password: pgcmpe295!

test:
  adapter: postgresql
  encoding: unicode
  database: tracking_test
  username: ec2-user
  password: pgcmpe295!

